@extends('app')

@section('css')
@endsection

@section('content')
<div class="divider"></div>

<div class="container" style="padding: 60px;">
  <div class="row">
    <!-- <h2 class="margin">ACER</h2> -->
    <!-- <div class="border-line"></div> -->

    <div class="row">
        <div class="col-md-12 col-xs-12">
         <h2 class="text-center blue"><strong>Red Hat Enterprise Clustering and Storage Management</strong></h2>
         <br>
         <h3 class="blue"><strong>Design and deploy a high availability cluster</strong></h3>
         <br>
         <p>The intensive, hands-on Red Hat® High Availability Clustering (RH436) course teaches storage management, the Red Hat High Availability Add-On, and the shared storage technology delivered by Red Hat Global File System 2 (GFS2) and Red Hat Gluster Storage.</p>


         <h4 class="blue">Course Overview</h4>
         <p>Created for senior Linux® system administrators, this 4-day course strongly emphasizes lab-based activities. You’ll learn how to deploy and manage shared storage and server clusters that provide highly available network services to a mission-critical enterprise environment.</p>
         <br>
         <p>This course also helps you prepare for the Red Hat Certificate of Expertise in High Availability Clustering exam (EX436)</p>


         <h4 class="blue">Content summary</h4>
         <ul>
           <li>Install and configure a Pacemaker-based high availability cluster</li>
           <li>Create and manage highly available services</li>
           <li>Troubleshoot common cluster issues</li>
           <li>Work with shared storage (iSCSI) and configure multipathing</li>
           <li>Configure GFS2 file systems</li>
          
         </ul>

         <h4 class="blue">Audience and prerequisite</h4>
            <ul>
                <li>Senior Linux system administrator responsible for maximizing resilency through high-availability clustering services and using fault-tolerant shared storage technologies</li>
            </ul>


         <h4 class="blue">Prerequisites for this course</h4>
            <ul>
                <li>If you want to take this course without the exam (RH436) and have not earned your RHCE certification, you can confirm that you have the necessary knowledege by passing the online skills assessment</li>
            </ul>


         <h4 class="blue">Outline for this course</h4>

         <p><b>Clusters and storage</b></p>
         <p>Get an overview of storage and cluster technologies.</p>
         <br>

         <p><b>Create high-availability clusters</b></p>
         <p>Review and create the architecture of Peacemaker-based high-availability clusters</p>
         <br>

         <p><b>Nodes and quorum</b></p>
         <p>Review cluster node membership and how quorum is used to control clusters.</p>
         <br>

         <p><b>Fencing</b></p>
         <p>Understand fencing and fencing configuration.</p>
         <br>

         <p><b>Resource groups</b></p>
         <p>Create and configure simple resource grioups to provide high-availability services to clients.</p>
         <br>

         <p><b>Troubleshoot high-availability clusters</b></p>
         <p>Identify and troubleshoot cluster problems.</p>
         <br>

         <p><b>Complex resource groups</b></p>
         <p>Control complex resource groups by using constraints.</p>
         <br>

        <p><b>Two-node clusters</b></p>
         <p>Identify and work around two-node clusters issues.</p>
         <br>

        <p><b>ISCSI initiators</b></p>
         <p>Manage iSCSI initiators for access to shared storage</p>
         <br>

        <p><b>Multipath Storage</b></p>
         <p>Configure redundant storage access</p>
         <br>

        <p><b>Logical volume manager (LVM) clusters</b></p>
         <p>Manage cluster LV.</p>
         <br>

        <p><b>Global File System 2</b></p>
         <p>Create symmetric shared file systems.</p>
         <br>


        <p><b>Eliminate single points of failure</b></p>
         <p>Configure remote logging to use transport layer encryption and manage additional logs generated by remote systems.</p>
         <br>

        <p><b>Comprehensive review</b></p>
         <p>Set up high-availability services and storage.</p>
         <br>

         <h4 class="blue">Recommended next exam or course</h4>
         <p><b>Red Hat Certificate of Expertise in High Availability Clustering exam (EX436)</b></p>
         <p>Hands-on, performance-based, 4 hour exam</p>
         <br>

         <p><b>Red Hat Enterprise Deployment and Systems Management (RH401)</b></p>
         <p>Equips senior administrator for large-scale deployment and mangement of Red Hat Enterprise Linux systems, including Red Hat Network Satellite Server.</p>
         <br>

         <p><b>Red Hat Enterprise Performance Tuning (RH442)</b></p>
         <p>Gives senior administrators methodology and experience with performance tuning and capacity planning for Red Hat Enterprise Linux</p>


        </div>


    </div>

    <div>
      
    </div>
  </div>
</div>

@endsection